version: "3"

services:
  janus:
    build: ./janus

    container_name: docker-janus
#    image: stryng/d-j:v1
    environment:
    - LD_LIBRARY_PATH=/usr/local/lib 
    ports:
      - 8088:8088
      - 8188:8188
    volumes:
      - ./janus/etc:/opt/janus/etc/janus
    command: "/opt/janus/bin/janus -S stun.l.google.com:19302"
